# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6139926ed854e16943ad249e8b7da31b9fe51c46921688d6c2f1cd86194d0ad5151459acdd4e4c71bff5fe94c9df86e64a8807511e272c6549a31a525cd30829

test:
  secret_key_base: 1f473cd801094b4b913d932594cec47ee9ed44a204cf37315077a17eac2c5437139f32531edee768425cf3f93f4b2d46a8d7f9ec1ba0fe7ad2f5bafd025864e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
